from pathlib import Path


# Project root and file-system paths.
PROJECT_ROOT = Path(__file__).resolve().parents[1]

TOKENIZER_DIR = PROJECT_ROOT / "tokenizer"
TOKENIZER_PATH = TOKENIZER_DIR / "tokenizer.json"

DATA_DIR = PROJECT_ROOT / "data"
TINYSTORIES_DIR = DATA_DIR / "tinystories"
HF_CACHE_DIR = DATA_DIR / "hf_cache"
TOKENIZED_DATA_DIR = DATA_DIR / "tokenized"

TRAIN_TOKENS_PATH = TOKENIZED_DATA_DIR / "train.bin"
VALIDATION_TOKENS_PATH = TOKENIZED_DATA_DIR / "validation.bin"

CHECKPOINT_DIR = PROJECT_ROOT / "checkpoints"
LATEST_CHECKPOINT = CHECKPOINT_DIR / "latest.pt"


# Tokenizer configuration.
VOCAB_SIZE = 8192

PAD_TOKEN = "<pad>"
UNK_TOKEN = "<unk>"
BOS_TOKEN = "<bos>"
EOS_TOKEN = "<eos>"

SPECIAL_TOKENS = [PAD_TOKEN, UNK_TOKEN, BOS_TOKEN, EOS_TOKEN]


# Transformer architecture.
CONTEXT_LENGTH = 512
D_MODEL = 512
N_LAYERS = 6
N_HEADS = 8
D_HEAD = D_MODEL // N_HEADS
D_FF = 2048

assert D_MODEL % N_HEADS == 0


# Training configuration.
BATCH_SIZE = 32
GRADIENT_ACCUMULATION_STEPS = 1

LEARNING_RATE = 1e-4
MIN_LEARNING_RATE = 1e-5
WARMUP_STEPS = 500

ADAM_BETA_1 = 0.9
ADAM_BETA_2 = 0.95
WEIGHT_DECAY = 0.1

MAX_GRAD_NORM = 1.0

# Approximately 600M total training tokens.
TRAINING_STEPS = 36_622
RUN_UNTIL_STEP = 36_622

VALIDATION_INTERVAL = 250
VALIDATION_BATCHES = 20

CHECKPOINT_INTERVAL = 250
MILESTONE_CHECKPOINT_INTERVAL = 5_000

# Always resume from the newest rolling checkpoint.
RESUME_CHECKPOINT = LATEST_CHECKPOINT
